name: Docker Image CI

on:
  push:
    branches: [ main ]
    paths: [ 'Dockerfile']
  pull_request:
    branches: [ main ]
    paths: [ 'Dockerfile']

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build and publish images
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: hyr326/ldap-ssp
        tags: "latest"
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
